services:
    trollroom:
        container_name: trollroom
        image: ghcr.io/noagenda/trollroom:${APP_TAG:-local}
        build: .
        # todo fix development environment
        #environment:
        #    NODE_ENV: development
        ports:
            - "9000:9000"
        volumes:
            - "./:/srv"
