services:
    trollroom:
        container_name: trollroom
        image: ghcr.io/noagenda/trollroom:${APP_TAG:-local}
        build: .
        working_dir: /srv
        environment:
            NODE_ENV: production
        env_file:
            - .env
        ports:
            - "9000:9000"
        volumes:
            - "./:/srv"
