services:
    trollroom:
        container_name: trollroom
        image: ghcr.io/noagenda/trollroom:${APP_TAG:-local}
        build: .
        working_dir: /srv
        ports:
            - "9000:9000"
        volumes:
            - "./config:/root/.thelounge"
            - "./:/srv"
